clients:
- {avatar: 'client-1.jpg',
  name: 'Lorna Dane',
  title: 'Director of Design, OnToText',
  comment: '<p><strong>While we all felt that x was a great</strong> asset to our team — and really worked hard to understand our products from the point of view of the customer — we also all agree he should shower more often.</p>',
  logo: 'logo1.png'}
- {avatar: 'client-2.jpg',
  name: 'Hank McCoy',
  title: 'Eater of Salad, Antartica Int.',
  comment: '<p><strong>Working with x was the highlight of my career.</strong> Other moments of note were collecting the largest number of paperclips in the office, and winning a trophy for saying "uh huh, and then what?" 30 times in a row to my girlfriend without her noticing.</p>',
  logo: 'logo2.png'}
- {avatar: 'client-3.jpg',
  name: 'Stacy Lang',
  title: 'Social Media Girl, Quebec Int.',
  comment: '<p><strong>Yea, I guess hes good at computers or something,</strong> but let me ask you this: If a cat always lands on its feet, and buttered bread always lands butter side down, what would happen if you tied buttered bread on top of a cat?</p>',
  logo: 'logo3.png'}
- {avatar: 'client-4.jpg',
  name: 'Cleatus Cassidy',
  title: 'VP of Helmut, Lorem Sorem LLC.',
  comment: '<p><strong>Back in old country</strong> only nerds who is playing on computers. Now all bros is wanting to make codes and junk. I lost foot in war. You dont see girls asking me about homework.</p>',
  logo: 'logo4.png'}