#Website Settings
title: Portfolio Site
email: sam_hake@live.co.uk
description: "Design | Portfolio | Project"

# Build settings

markdown: kramdown
permalink: pretty

port: 4000

sass:
  sass_dir: assets/css
  style: :nested 